// ─────────────────────────────────────────────────────────────
// Generate machine-verifiable submission evidence for the DynamoDB deliverables.
//
//   pnpm proof
//
// Writes to docs/proof/:
//   table-description.json  — live DescribeTable: keys, GSI1/GSI2, Streams,
//                             billing mode, item count (the "storage config
//                             screenshot proving DynamoDB usage", as raw data).
//   throttle-metrics.json   — CloudWatch WriteThrottleEvents for the table + GSIs
//                             over the last 3h (the load-test proof, as numbers).
//   summary.md              — a human-readable digest to paste into the submission.
//
// Pair these JSON files with console screenshots; the numbers are the receipts.
// ─────────────────────────────────────────────────────────────
import { mkdirSync, writeFileSync } from 'node:fs'
import { DescribeTableCommand } from '@aws-sdk/client-dynamodb'
import {
  CloudWatchClient,
  GetMetricStatisticsCommand,
} from '@aws-sdk/client-cloudwatch'
import { ddbClient, TABLE, REGION } from './aws.mjs'

const ddb = ddbClient()
const cw = new CloudWatchClient({ region: REGION })
const OUT = new URL('../docs/proof/', import.meta.url).pathname

async function describe() {
  const { Table } = await ddb.send(new DescribeTableCommand({ TableName: TABLE }))
  return {
    tableName: Table.TableName,
    region: REGION,
    billingMode: Table.BillingModeSummary?.BillingMode ?? 'PROVISIONED',
    itemCount: Table.ItemCount,
    keySchema: Table.KeySchema,
    attributeDefinitions: Table.AttributeDefinitions,
    streamSpecification: Table.StreamSpecification,
    latestStreamArn: Table.LatestStreamArn,
    globalSecondaryIndexes: (Table.GlobalSecondaryIndexes ?? []).map((g) => ({
      indexName: g.IndexName,
      keySchema: g.KeySchema,
      projection: g.Projection,
      itemCount: g.ItemCount,
    })),
    replicas: Table.Replicas ?? [], // populated when Global Tables are enabled
  }
}

async function throttles() {
  const end = new Date()
  const start = new Date(end.getTime() - 3 * 3600 * 1000)
  const base = {
    Namespace: 'AWS/DynamoDB',
    MetricName: 'WriteThrottleEvents',
    StartTime: start,
    EndTime: end,
    Period: 60,
    Statistics: ['Sum'],
  }
  const dims = [
    { label: 'table', Dimensions: [{ Name: 'TableName', Value: TABLE }] },
    { label: 'GSI1', Dimensions: [{ Name: 'TableName', Value: TABLE }, { Name: 'GlobalSecondaryIndexName', Value: 'GSI1' }] },
    { label: 'GSI2', Dimensions: [{ Name: 'TableName', Value: TABLE }, { Name: 'GlobalSecondaryIndexName', Value: 'GSI2' }] },
  ]
  const out = {}
  for (const d of dims) {
    const res = await cw.send(new GetMetricStatisticsCommand({ ...base, Dimensions: d.Dimensions }))
    const points = (res.Datapoints ?? []).sort((a, b) => a.Timestamp - b.Timestamp)
    out[d.label] = {
      totalThrottleEvents: points.reduce((s, p) => s + (p.Sum ?? 0), 0),
      datapoints: points.map((p) => ({ t: p.Timestamp, sum: p.Sum })),
    }
  }
  return out
}

async function main() {
  mkdirSync(OUT, { recursive: true })
  console.log(`[proof] region=${REGION} table=${TABLE}`)

  const desc = await describe()
  writeFileSync(`${OUT}table-description.json`, JSON.stringify(desc, null, 2))
  console.log('[proof] ✓ docs/proof/table-description.json')

  let tm = {}
  try {
    tm = await throttles()
    writeFileSync(`${OUT}throttle-metrics.json`, JSON.stringify(tm, null, 2))
    console.log('[proof] ✓ docs/proof/throttle-metrics.json')
  } catch (err) {
    console.warn('[proof] CloudWatch metrics skipped (needs cloudwatch:GetMetricStatistics):', err.name)
  }

  const md = `# PulseRooms — DynamoDB evidence (auto-generated)

_Generated by \`pnpm proof\`. Pair with console screenshots._

## Table: \`${desc.tableName}\` (${desc.region})
- Billing: **${desc.billingMode}**
- Items: ${desc.itemCount}
- Streams: **${desc.streamSpecification?.StreamEnabled ? desc.streamSpecification.StreamViewType : 'disabled'}**
- Stream ARN: \`${desc.latestStreamArn ?? '—'}\`
- Base key: ${desc.keySchema?.map((k) => `${k.AttributeName}(${k.KeyType})`).join(', ')}
- Global Tables replicas: ${desc.replicas.length ? desc.replicas.map((r) => r.RegionName).join(', ') : 'none (single-region)'}

### Global Secondary Indexes
${desc.globalSecondaryIndexes
  .map(
    (g) =>
      `- **${g.indexName}** — ${g.keySchema.map((k) => `${k.AttributeName}(${k.KeyType})`).join(', ')} · projection ${g.projection?.ProjectionType}`,
  )
  .join('\n')}

## WriteThrottleEvents (last 3h)
${
  Object.keys(tm).length
    ? Object.entries(tm)
        .map(([k, v]) => `- ${k}: **${v.totalThrottleEvents}** throttle events`)
        .join('\n')
    : '_CloudWatch metrics unavailable (permission) — capture from the console instead._'
}
`
  writeFileSync(`${OUT}summary.md`, md)
  console.log('[proof] ✓ docs/proof/summary.md')
  console.log('\n' + md)
}

main().catch((err) => {
  console.error('[proof] FAILED:', err)
  process.exit(1)
})
